apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-claim
spec:
  storageClassName: "pipeline-nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-nfs
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "pipeline-nfs"
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.55
    path: "/var/nfs/pipeline"