apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: ingress
spec:
  rules:
    - host: pipeline-pipelines-example.118.163.91.247.nip.io
      http:
        paths:
          - backend:
              serviceName: el-listener
              servicePort: 8080
